---
# tasks file for ansible-role-logrotate

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ logrotate_log_dir }}"
    mode: 0755
    owner: "{{ logrotate_user }}"
    group: "{{ logrotate_group }}"
    state: directory
  notify: Restart logrotate

- name: Create db directory
  file:
    path: "{{ logrotate_db_dir }}"
    mode: 0755
    owner: "{{ logrotate_user }}"
    group: "{{ logrotate_group }}"
    state: directory
  notify: Restart logrotate

- name: Create logrotate.conf
  template:
    src: logrotate.conf.j2
    dest: "{{ logrotate_conf_file }}"
    validate: echo %s
  notify: Restart logrotate

- name: Start logrotate
  service:
    name: "{{ logrotate_service }}"
    enabled: true
    state: started
